"""added cas_sanitized to substances

Revision ID: 06e9881a7476
Revises: ba667062730a
Create Date: 2017-04-21 01:17:07.572045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e9881a7476'
down_revision = 'ba667062730a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('criteria', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('criteria', 'state_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('substance', sa.Column('cas_sanitized', sa.String(length=255), nullable=True))
    op.alter_column('substance', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('substance', 'cas',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('substance', 'criteria',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('substance', 'hard_ref',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('substance', 'precision',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('substance', 'sort',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('substance', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('substance', 'unit',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('substance', 'unit',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('substance', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('substance', 'sort',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('substance', 'precision',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('substance', 'hard_ref',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('substance', 'criteria',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('substance', 'cas',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('substance', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('substance', 'cas_sanitized')
    op.alter_column('criteria', 'state_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('criteria', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
