"""add url to lab

Revision ID: 07fc93aa3f72
Revises: 1a94f7592697
Create Date: 2017-02-24 04:56:26.057023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07fc93aa3f72'
down_revision = '1a94f7592697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab', sa.Column('url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab', 'url')
    # ### end Alembic commands ###
