"""removed project_id fk from Upload model

Revision ID: 0bf9f0276ff8
Revises: ba8709fd7e32
Create Date: 2017-03-21 18:43:46.613183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf9f0276ff8'
down_revision = 'ba8709fd7e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'upload_project_id_fkey', 'upload', type_='foreignkey')
    op.drop_column('upload', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'upload_project_id_fkey', 'upload', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###
