"""change roles to singular

Revision ID: 1a94f7592697
Revises: 63819a8dbc41
Create Date: 2017-02-24 04:40:47.854149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a94f7592697'
down_revision = '63819a8dbc41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.create_foreign_key(None, 'site', 'lab', ['laboratory_id'], ['laboratory_id'])
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_constraint(None, 'site', type_='foreignkey')
    op.create_table('roles_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'role.id'], name=u'roles_users_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'roles_users_user_id_fkey')
    )
    # ### end Alembic commands ###
