"""modified site data model extensively

Revision ID: 23f627a97dcb
Revises: 38abfa5d345a
Create Date: 2017-05-08 00:33:53.433069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f627a97dcb'
down_revision = '38abfa5d345a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_data', sa.Column('contact_qc', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('depth_to_groundwater', sa.String(length=255), nullable=True))
    op.add_column('site_data', sa.Column('drinking_water_affected_currently', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('drinking_water_affected_municiple', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('drinking_water_affected_municiple_num_wells', sa.Integer(), nullable=True))
    op.add_column('site_data', sa.Column('drinking_water_affected_previously', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('drinking_water_affected_private', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('drinking_water_affected_private_num_wells', sa.Integer(), nullable=True))
    op.add_column('site_data', sa.Column('drinking_water_affected_public', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('drinking_water_affected_public_num_wells', sa.Integer(), nullable=True))
    op.add_column('site_data', sa.Column('migrating_napl_actions_taken', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('migrating_napl_present_currently', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('mobile_napl_present_currently', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('mobile_napl_present_previously', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('mobile_napl_present_recovered', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('mobile_napl_present_recovered_date', sa.DateTime(), nullable=True))
    op.add_column('site_data', sa.Column('mobile_napl_present_recovered_gallons', sa.String(length=255), nullable=True))
    op.add_column('site_data', sa.Column('previous_classification', sa.Integer(), nullable=True))
    op.add_column('site_data', sa.Column('report_type', sa.String(length=255), nullable=True))
    op.add_column('site_data', sa.Column('report_type_other', sa.String(length=255), nullable=True))
    op.add_column('site_data', sa.Column('site_classification', sa.Integer(), nullable=True))
    op.add_column('site_data', sa.Column('substances_released_diesel', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('substances_released_ethanol', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('substances_released_ethanol_e10', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('substances_released_ethanol_e85', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('substances_released_gasoline', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('substances_released_other', sa.String(length=255), nullable=True))
    op.add_column('site_data', sa.Column('surface_water_contaminated', sa.Boolean(), nullable=True))
    op.add_column('site_data', sa.Column('type_of_rbca_evaluation', sa.String(length=255), nullable=True))
    op.add_column('site_data', sa.Column('wellhead_protection_zone', sa.Boolean(), nullable=True))
    op.drop_column('site_data', 'free_product_recovered')
    op.drop_column('site_data', 'free_product_previously')
    op.drop_column('site_data', 'maximum_mtbe_concentration')
    op.drop_column('site_data', 'type_of_product_released')
    op.drop_column('site_data', 'mtbe_detected')
    op.drop_column('site_data', 'michigan_rbca_site_classification')
    op.drop_column('site_data', 'free_product_recovered_since_last_report')
    op.drop_column('site_data', 'mera_site_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_data', sa.Column('mera_site_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('site_data', sa.Column('free_product_recovered_since_last_report', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('site_data', sa.Column('michigan_rbca_site_classification', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('site_data', sa.Column('mtbe_detected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('site_data', sa.Column('type_of_product_released', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('site_data', sa.Column('maximum_mtbe_concentration', sa.REAL(), autoincrement=False, nullable=True))
    op.add_column('site_data', sa.Column('free_product_previously', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('site_data', sa.Column('free_product_recovered', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('site_data', 'wellhead_protection_zone')
    op.drop_column('site_data', 'type_of_rbca_evaluation')
    op.drop_column('site_data', 'surface_water_contaminated')
    op.drop_column('site_data', 'substances_released_other')
    op.drop_column('site_data', 'substances_released_gasoline')
    op.drop_column('site_data', 'substances_released_ethanol_e85')
    op.drop_column('site_data', 'substances_released_ethanol_e10')
    op.drop_column('site_data', 'substances_released_ethanol')
    op.drop_column('site_data', 'substances_released_diesel')
    op.drop_column('site_data', 'site_classification')
    op.drop_column('site_data', 'report_type_other')
    op.drop_column('site_data', 'report_type')
    op.drop_column('site_data', 'previous_classification')
    op.drop_column('site_data', 'mobile_napl_present_recovered_gallons')
    op.drop_column('site_data', 'mobile_napl_present_recovered_date')
    op.drop_column('site_data', 'mobile_napl_present_recovered')
    op.drop_column('site_data', 'mobile_napl_present_previously')
    op.drop_column('site_data', 'mobile_napl_present_currently')
    op.drop_column('site_data', 'migrating_napl_present_currently')
    op.drop_column('site_data', 'migrating_napl_actions_taken')
    op.drop_column('site_data', 'drinking_water_affected_public_num_wells')
    op.drop_column('site_data', 'drinking_water_affected_public')
    op.drop_column('site_data', 'drinking_water_affected_private_num_wells')
    op.drop_column('site_data', 'drinking_water_affected_private')
    op.drop_column('site_data', 'drinking_water_affected_previously')
    op.drop_column('site_data', 'drinking_water_affected_municiple_num_wells')
    op.drop_column('site_data', 'drinking_water_affected_municiple')
    op.drop_column('site_data', 'drinking_water_affected_currently')
    op.drop_column('site_data', 'depth_to_groundwater')
    op.drop_column('site_data', 'contact_qc')
    # ### end Alembic commands ###
