"""added free_product bool to SampleValue - this is like floating gasoline, no need to send to the lab

Revision ID: 25caf3f73fb8
Revises: 599eef56766c
Create Date: 2017-06-21 16:44:34.415969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25caf3f73fb8'
down_revision = '599eef56766c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_value', sa.Column('free_product', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_value', 'free_product')
    # ### end Alembic commands ###
