"""commented out mobile_napl_recovered to date

Revision ID: 26bab668fb30
Revises: 4d007f02678b
Create Date: 2017-05-10 07:17:56.063267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26bab668fb30'
down_revision = '4d007f02678b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_data', 'mobile_napl_present_recovered_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_data', sa.Column('mobile_napl_present_recovered_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
