"""add pending field

Revision ID: 3210764d11ad
Revises: e7392ade6a19
Create Date: 2017-02-26 08:04:35.576010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3210764d11ad'
down_revision = 'e7392ade6a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pending', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pending')
    # ### end Alembic commands ###
