"""added upload type to Upload


Revision ID: 34ccffafedd4
Revises: ef491f2a0812
Create Date: 2017-04-04 08:11:35.317959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ccffafedd4'
down_revision = 'ef491f2a0812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('upload_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'upload_type')
    # ### end Alembic commands ###
