"""add sitemaps

Revision ID: 37b8c276b8d0
Revises: 3af7d65123a1
Create Date: 2017-02-10 15:48:35.469928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b8c276b8d0'
down_revision = '3af7d65123a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_map',
    sa.Column('site_map_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.site_id'], ),
    sa.PrimaryKeyConstraint('site_map_id')
    )
    op.create_table('site_map_well',
    sa.Column('site_map_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('xpos', sa.Integer(), nullable=False),
    sa.Column('ypos', sa.Integer(), nullable=False),
    sa.Column('xpos_fields', sa.Integer(), nullable=False),
    sa.Column('ypos_fields', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.site_id'], ),
    sa.ForeignKeyConstraint(['site_map_id'], ['site_map.site_map_id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['well.well_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_map_well')
    op.drop_table('site_map')
    # ### end Alembic commands ###
