"""added id col to sitedata

Revision ID: 38abfa5d345a
Revises: 69c60116bdcd
Create Date: 2017-05-07 22:22:28.849831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38abfa5d345a'
down_revision = '69c60116bdcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
