"""delete columns

Revision ID: 3f88eba94f15
Revises: 23f627a97dcb
Create Date: 2017-05-08 02:23:50.502415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f88eba94f15'
down_revision = '23f627a97dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'qaqc_equipmentblanks')
    op.drop_column('site', 'qaqc_msmsds_per_samples')
    op.drop_column('site', 'qaqc_msmsds_test_ids')
    op.drop_column('site', 'qaqc_duplicates')
    op.drop_column('site', 'qaqc_msmsds')
    op.drop_column('site', 'qaqc_tripblanks_per_samples')
    op.drop_column('site', 'qaqc_fieldblanks_test_ids')
    op.drop_column('site', 'qaqc_duplicates_well_ids')
    op.drop_column('site', 'qaqc_msmsds_type')
    op.drop_column('site', 'qaqc_duplicates_type')
    op.drop_column('site', 'qaqc_equipmentblanks_test_ids')
    op.drop_column('site', 'qaqc_tripblanks')
    op.drop_column('site', 'qaqc_equipmentblanks_type')
    op.drop_column('site', 'qaqc_msmsds_well_ids')
    op.drop_column('site', 'qaqc_tripblanks_test_ids')
    op.drop_column('site', 'qaqc_fieldblanks')
    op.drop_column('site', 'qaqc_duplicates_per_samples')
    op.drop_column('site', 'qaqc_duplicates_test_ids')
    op.drop_column('site', 'qaqc_fieldblanks_per_samples')
    op.drop_column('site', 'qaqc_fieldblanks_type')
    op.drop_column('site', 'qaqc_tripblanks_type')
    op.drop_column('site', 'qaqc_equipmentblanks_per_samples')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('qaqc_equipmentblanks_per_samples', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_tripblanks_type', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_fieldblanks_type', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_fieldblanks_per_samples', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_duplicates_test_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_duplicates_per_samples', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_fieldblanks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_tripblanks_test_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_msmsds_well_ids', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_equipmentblanks_type', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_tripblanks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_equipmentblanks_test_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_duplicates_type', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_msmsds_type', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_duplicates_well_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_fieldblanks_test_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_tripblanks_per_samples', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_msmsds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_duplicates', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_msmsds_test_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_msmsds_per_samples', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_equipmentblanks', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
