"""added filestack_handle to wellimage

Revision ID: 409247407c67
Revises: b0351a9b353a
Create Date: 2017-04-28 04:12:17.833433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409247407c67'
down_revision = 'b0351a9b353a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('well_image', sa.Column('filestack_handle', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('well_image', 'filestack_handle')
    # ### end Alembic commands ###
