"""add qaqc column backs with correct type

Revision ID: 4d007f02678b
Revises: 3f88eba94f15
Create Date: 2017-05-08 02:24:38.212837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d007f02678b'
down_revision = '3f88eba94f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('qaqc_duplicates', sa.Boolean(), nullable=True))
    op.add_column('site', sa.Column('qaqc_duplicates_per_samples', sa.Integer(), nullable=True))
    op.add_column('site', sa.Column('qaqc_duplicates_test_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('qaqc_duplicates_type', sa.String(length=16), nullable=True))
    op.add_column('site', sa.Column('qaqc_duplicates_well_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('qaqc_equipmentblanks', sa.Boolean(), nullable=True))
    op.add_column('site', sa.Column('qaqc_equipmentblanks_per_samples', sa.Integer(), nullable=True))
    op.add_column('site', sa.Column('qaqc_equipmentblanks_test_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('qaqc_equipmentblanks_type', sa.String(length=16), nullable=True))
    op.add_column('site', sa.Column('qaqc_fieldblanks', sa.Boolean(), nullable=True))
    op.add_column('site', sa.Column('qaqc_fieldblanks_per_samples', sa.Integer(), nullable=True))
    op.add_column('site', sa.Column('qaqc_fieldblanks_test_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('qaqc_fieldblanks_type', sa.String(length=16), nullable=True))
    op.add_column('site', sa.Column('qaqc_msmsds', sa.Boolean(), nullable=True))
    op.add_column('site', sa.Column('qaqc_msmsds_per_samples', sa.Integer(), nullable=True))
    op.add_column('site', sa.Column('qaqc_msmsds_test_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('qaqc_msmsds_type', sa.String(length=16), nullable=True))
    op.add_column('site', sa.Column('qaqc_msmsds_well_ids', sa.String(length=255), nullable=True))
    op.add_column('site', sa.Column('qaqc_tripblanks', sa.Boolean(), nullable=True))
    op.add_column('site', sa.Column('qaqc_tripblanks_per_samples', sa.Integer(), nullable=True))
    op.add_column('site', sa.Column('qaqc_tripblanks_test_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('site', sa.Column('qaqc_tripblanks_type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'qaqc_tripblanks_type')
    op.drop_column('site', 'qaqc_tripblanks_test_ids')
    op.drop_column('site', 'qaqc_tripblanks_per_samples')
    op.drop_column('site', 'qaqc_tripblanks')
    op.drop_column('site', 'qaqc_msmsds_well_ids')
    op.drop_column('site', 'qaqc_msmsds_type')
    op.drop_column('site', 'qaqc_msmsds_test_ids')
    op.drop_column('site', 'qaqc_msmsds_per_samples')
    op.drop_column('site', 'qaqc_msmsds')
    op.drop_column('site', 'qaqc_fieldblanks_type')
    op.drop_column('site', 'qaqc_fieldblanks_test_ids')
    op.drop_column('site', 'qaqc_fieldblanks_per_samples')
    op.drop_column('site', 'qaqc_fieldblanks')
    op.drop_column('site', 'qaqc_equipmentblanks_type')
    op.drop_column('site', 'qaqc_equipmentblanks_test_ids')
    op.drop_column('site', 'qaqc_equipmentblanks_per_samples')
    op.drop_column('site', 'qaqc_equipmentblanks')
    op.drop_column('site', 'qaqc_duplicates_well_ids')
    op.drop_column('site', 'qaqc_duplicates_type')
    op.drop_column('site', 'qaqc_duplicates_test_ids')
    op.drop_column('site', 'qaqc_duplicates_per_samples')
    op.drop_column('site', 'qaqc_duplicates')
    # ### end Alembic commands ###
