"""added photo_url to users model

Revision ID: 5297dbe6a18e
Revises: 96a6b0dbd5c3
Create Date: 2017-03-19 19:06:01.534625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5297dbe6a18e'
down_revision = '96a6b0dbd5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo_url')
    # ### end Alembic commands ###
