"""add date col as datetime

Revision ID: 54408ca70b38
Revises: 8728363283dd
Create Date: 2017-04-07 09:27:06.551048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54408ca70b38'
down_revision = '8728363283dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'date')
    # ### end Alembic commands ###
