"""add secondary models

Revision ID: 55cae16d0d7d
Revises: 3c74a9b7d9f2
Create Date: 2017-02-08 21:52:12.486010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55cae16d0d7d'
down_revision = '3c74a9b7d9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_data',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('mera_site_id', sa.String(length=255), nullable=False),
    sa.Column('date_release_discovered', sa.String(length=255), nullable=False),
    sa.Column('confirmed_release_number', sa.String(length=255), nullable=False),
    sa.Column('type_of_product_released', sa.String(length=255), nullable=False),
    sa.Column('free_product_recovered_since_last_report', sa.String(length=255), nullable=False),
    sa.Column('free_product_previously', sa.Boolean(), nullable=False),
    sa.Column('free_product_recovered', sa.String(length=255), nullable=False),
    sa.Column('vapors_in_confined_space', sa.Boolean(), nullable=False),
    sa.Column('groundwater_flow_direction', sa.String(length=255), nullable=False),
    sa.Column('point_of_release_to_private_well', sa.String(length=255), nullable=False),
    sa.Column('point_of_release_to_municipal_well', sa.String(length=255), nullable=False),
    sa.Column('point_of_release_to_surface_water', sa.String(length=255), nullable=False),
    sa.Column('soil_remediated_since_last_report', sa.String(length=255), nullable=False),
    sa.Column('groundwater_remediated_since_last_report', sa.String(length=255), nullable=False),
    sa.Column('soil_remediated', sa.String(length=255), nullable=False),
    sa.Column('groundwater_remediated', sa.String(length=255), nullable=False),
    sa.Column('michigan_rbca_site_classification', sa.Integer(), nullable=False),
    sa.Column('contamination_migrated_off_site', sa.Boolean(), nullable=False),
    sa.Column('impacted_parties_notified', sa.Boolean(), nullable=False),
    sa.Column('mtbe_detected', sa.Boolean(), nullable=False),
    sa.Column('maximum_mtbe_concentration', sa.Float(precision=10), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.site_id'], )
    )
    op.create_table('well_date',
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('gaugeonly', sa.Boolean(), nullable=False),
    sa.Column('test_ids', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['well.well_id'], )
    )
    op.create_table('well_date_set',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.site_id'], )
    )
    op.create_table('well_image',
    sa.Column('well_image_id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('last_modified', sa.Integer(), nullable=False),
    sa.Column('height_md', sa.Integer(), nullable=False),
    sa.Column('width_md', sa.Integer(), nullable=False),
    sa.Column('width_sm', sa.Integer(), nullable=False),
    sa.Column('height_sm', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['well.well_id'], ),
    sa.PrimaryKeyConstraint('well_image_id')
    )
    op.create_table('substance_state_names',
    sa.Column('substance_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['state.state_id'], ),
    sa.ForeignKeyConstraint(['substance_id'], ['substance.substance_id'], )
    )
    op.create_table('substances_sites',
    sa.Column('substance_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.site_id'], ),
    sa.ForeignKeyConstraint(['substance_id'], ['substance.substance_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('substances_sites')
    op.drop_table('substance_state_names')
    op.drop_table('well_image')
    op.drop_table('well_date_set')
    op.drop_table('well_date')
    op.drop_table('site_data')
    # ### end Alembic commands ###
