"""added field_data bool to Substance model


Revision ID: 599eef56766c
Revises: 7e83804acc70
Create Date: 2017-06-21 13:22:16.625340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599eef56766c'
down_revision = '7e83804acc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('substance', sa.Column('field_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('substance', 'field_data')
    # ### end Alembic commands ###
