"""ignore null in company

Revision ID: 5a002893b6f6
Revises: 0bf9f0276ff8
Create Date: 2017-03-21 18:44:55.305299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a002893b6f6'
down_revision = '0bf9f0276ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('company', 'cell',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('company', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('company', 'contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('company', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('company', 'fax',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('company', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('company', 'phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('company', 'state',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('company', 'zip',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'zip',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('company', 'state',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('company', 'phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('company', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('company', 'fax',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('company', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('company', 'contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('company', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('company', 'cell',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('company', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
