"""switched qaqc_msmsds_well_ids to json type


Revision ID: 5e8522d5f128
Revises: ab9ec5041688
Create Date: 2017-06-15 07:58:04.442279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '5e8522d5f128'
down_revision = 'ab9ec5041688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE site ALTER COLUMN qaqc_duplicates_test_ids TYPE JSON USING qaqc_duplicates_test_ids::JSON')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE site ALTER COLUMN qaqc_duplicates_test_ids TYPE VARCHAR(255)')
    # ### end Alembic commands ###
