"""fix primary id sequences

Revision ID: 5eaf24d35f87
Revises: 5a002893b6f6
Create Date: 2017-03-21 19:01:54.587183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eaf24d35f87'
down_revision = '5a002893b6f6'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('company', 'id'), (SELECT MAX(id) FROM company)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('consultant', 'id'), (SELECT MAX(id) FROM consultant)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('criteria', 'id'), (SELECT MAX(id) FROM criteria)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('frequency', 'id'), (SELECT MAX(id) FROM frequency)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('lab', 'id'), (SELECT MAX(id) FROM lab)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('manager', 'id'), (SELECT MAX(id) FROM manager)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('office', 'id'), (SELECT MAX(id) FROM office)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('project', 'id'), (SELECT MAX(id) FROM project)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('role', 'id'), (SELECT MAX(id) FROM role)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('sample', 'id'), (SELECT MAX(id) FROM sample)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('sample_value', 'id'), (SELECT MAX(id) FROM sample_value)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('sampler', 'id'), (SELECT MAX(id) FROM sampler)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('schedule', 'id'), (SELECT MAX(id) FROM schedule)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('site', 'id'), (SELECT MAX(id) FROM site)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('site_map_well', 'id'), (SELECT MAX(id) FROM site_map_well)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('site_map', 'id'), (SELECT MAX(id) FROM site_map)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('state', 'id'), (SELECT MAX(id) FROM state)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('substance', 'id'), (SELECT MAX(id) FROM substance)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('substance_group', 'id'), (SELECT MAX(id) FROM substance_group)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('test', 'id'), (SELECT MAX(id) FROM test)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('test_material', 'id'), (SELECT MAX(id) FROM test_material)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('transaction', 'id'), (SELECT MAX(id) FROM transaction)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('well', 'id'), (SELECT MAX(id) FROM well)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('well_image', 'id'), (SELECT MAX(id) FROM well_image)+1)")
    op.execute("SELECT pg_catalog.setval(pg_get_serial_sequence('well_options', 'id'), (SELECT MAX(id) FROM well_options)+1)")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
