"""fix site sequence

Revision ID: 61dc6214242e
Revises: 70faf621fed8
Create Date: 2017-03-31 16:22:59.966394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61dc6214242e'
down_revision = '70faf621fed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('site', 'additional_consultant_ids',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('site', 'additional_owner_ids',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('site', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site', 'background',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('site', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('site', 'consultant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site', 'contact_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site', 'contact_phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site', 'county',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('site', 'facility_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site', 'history',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('site', 'lab_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'latitude',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('site', 'longitude',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('site', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('site', 'qaqc_duplicates',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'qaqc_duplicates_per_samples',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'qaqc_duplicates_test_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site', 'qaqc_duplicates_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('site', 'qaqc_duplicates_well_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site', 'qaqc_equipmentblanks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'qaqc_equipmentblanks_per_samples',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'qaqc_equipmentblanks_test_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site', 'qaqc_equipmentblanks_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('site', 'qaqc_fieldblanks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'qaqc_fieldblanks_per_samples',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'qaqc_fieldblanks_test_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site', 'qaqc_fieldblanks_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('site', 'qaqc_msmsds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'qaqc_msmsds_per_samples',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'qaqc_msmsds_test_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site', 'qaqc_msmsds_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('site', 'qaqc_msmsds_well_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site', 'qaqc_tripblanks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'qaqc_tripblanks_per_samples',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'qaqc_tripblanks_test_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site', 'qaqc_tripblanks_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('site', 'sampler_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'sort',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'start_sampling_on',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'state',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('site', 'state_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site', 'summary',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('site', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site', 'zip',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('site', 'zip',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('site', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site', 'summary',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('site', 'state_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'state',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('site', 'start_sampling_on',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'sort',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'sampler_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'qaqc_tripblanks_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('site', 'qaqc_tripblanks_test_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site', 'qaqc_tripblanks_per_samples',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'qaqc_tripblanks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'qaqc_msmsds_well_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site', 'qaqc_msmsds_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('site', 'qaqc_msmsds_test_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site', 'qaqc_msmsds_per_samples',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'qaqc_msmsds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'qaqc_fieldblanks_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('site', 'qaqc_fieldblanks_test_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site', 'qaqc_fieldblanks_per_samples',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'qaqc_fieldblanks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'qaqc_equipmentblanks_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('site', 'qaqc_equipmentblanks_test_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site', 'qaqc_equipmentblanks_per_samples',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'qaqc_equipmentblanks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'qaqc_duplicates_well_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site', 'qaqc_duplicates_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('site', 'qaqc_duplicates_test_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site', 'qaqc_duplicates_per_samples',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'qaqc_duplicates',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('site', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'longitude',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('site', 'latitude',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('site', 'lab_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'history',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('site', 'facility_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site', 'county',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('site', 'contact_phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site', 'contact_email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site', 'contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site', 'consultant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('site', 'background',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('site', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site', 'additional_owner_ids',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('site', 'additional_consultant_ids',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('site', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
