"""add lab users

Revision ID: 63819a8dbc41
Revises: 0dae246c7b99
Create Date: 2017-02-23 20:00:15.014555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63819a8dbc41'
down_revision = '0dae246c7b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labs_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.laboratory_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labs_users')
    # ### end Alembic commands ###
