"""added scale column to sitemap

Revision ID: 68c90ef0a089
Revises: d2ea3620e79f
Create Date: 2017-06-24 08:46:47.860213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c90ef0a089'
down_revision = 'd2ea3620e79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_map', sa.Column('scale', sa.Float(precision=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_map', 'scale')
    # ### end Alembic commands ###
