"""modified site_data table, added model

Revision ID: 69c60116bdcd
Revises: 93b5f572905d
Create Date: 2017-05-06 00:46:10.798186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c60116bdcd'
down_revision = '93b5f572905d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_data', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_data', 'id')
    # ### end Alembic commands ###
