"""added indexes to many db columns to speed up data import

Revision ID: 709d38298df2
Revises: 612386a42031
Create Date: 2017-06-28 07:57:37.795223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709d38298df2'
down_revision = '612386a42031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_site_title'), 'site', ['title'], unique=False)
    op.create_index(op.f('ix_substance_active'), 'substance', ['active'], unique=False)
    op.create_index(op.f('ix_substance_cas_sanitized'), 'substance', ['cas_sanitized'], unique=False)
    op.create_index(op.f('ix_substance_title'), 'substance', ['title'], unique=False)
    op.create_index(op.f('ix_substance_group_active'), 'substance_group', ['active'], unique=False)
    op.create_index(op.f('ix_substance_group_title'), 'substance_group', ['title'], unique=False)
    op.create_index(op.f('ix_well_title'), 'well', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_well_title'), table_name='well')
    op.drop_index(op.f('ix_substance_group_title'), table_name='substance_group')
    op.drop_index(op.f('ix_substance_group_active'), table_name='substance_group')
    op.drop_index(op.f('ix_substance_title'), table_name='substance')
    op.drop_index(op.f('ix_substance_cas_sanitized'), table_name='substance')
    op.drop_index(op.f('ix_substance_active'), table_name='substance')
    op.drop_index(op.f('ix_site_title'), table_name='site')
    # ### end Alembic commands ###
