"""forcing qaqc_msmsds_well_ids to json

Revision ID: 7e83804acc70
Revises: 5e8522d5f128
Create Date: 2017-06-15 08:14:41.221715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e83804acc70'
down_revision = '5e8522d5f128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('UPDATE site SET qaqc_msmsds_well_ids = \'{}\'')
    op.execute('ALTER TABLE site ALTER COLUMN qaqc_msmsds_well_ids TYPE JSON USING qaqc_msmsds_well_ids::JSON')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE site ALTER COLUMN qaqc_msmsds_well_ids TYPE VARCHAR(255)')
    # ### end Alembic commands ###
