"""switch labs to 1 to 1

Revision ID: 7f4fb1b8cd9c
Revises: 07fc93aa3f72
Create Date: 2017-02-24 18:48:25.029909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4fb1b8cd9c'
down_revision = '07fc93aa3f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labs_users')
    op.alter_column('lab', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'lab', ['url'])
    op.add_column('user', sa.Column('lab_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'lab', ['lab_id'], ['laboratory_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'lab_id')
    op.drop_constraint(None, 'lab', type_='unique')
    op.alter_column('lab', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_table('labs_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lab_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], [u'lab.laboratory_id'], name=u'labs_users_lab_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'labs_users_user_id_fkey')
    )
    # ### end Alembic commands ###
