"""moved paid_levels to samplevalues, added fk to sample and samplevalue for import

Revision ID: 85c136326052
Revises: 7c27b4a6b656
Create Date: 2017-04-24 13:06:36.448526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c136326052'
down_revision = '7c27b4a6b656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('upload_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample', 'upload', ['upload_id'], ['id'])
    op.drop_column('sample', 'import_id')
    op.drop_column('sample', 'paid_level_1')
    op.drop_column('sample', 'paid_level_2')
    op.add_column('sample_value', sa.Column('paid_level_1', sa.Boolean(), nullable=True))
    op.add_column('sample_value', sa.Column('paid_level_2', sa.Boolean(), nullable=True))
    op.add_column('sample_value', sa.Column('upload_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample_value', 'upload', ['upload_id'], ['id'])
    op.drop_column('sample_value', 'import_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_value', sa.Column('import_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sample_value', type_='foreignkey')
    op.drop_column('sample_value', 'upload_id')
    op.drop_column('sample_value', 'paid_level_2')
    op.drop_column('sample_value', 'paid_level_1')
    op.add_column('sample', sa.Column('paid_level_2', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('sample', sa.Column('paid_level_1', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('sample', sa.Column('import_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_column('sample', 'upload_id')
    # ### end Alembic commands ###
