"""drop date col

Revision ID: 8728363283dd
Revises: 267d414e9a7d
Create Date: 2017-04-07 09:26:10.805182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8728363283dd'
down_revision = '267d414e9a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
