"""changed Schedule related tables to allow nullable values

Revision ID: 8e147ebbcee8
Revises: df7e78400a3d
Create Date: 2017-04-07 09:08:59.440454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e147ebbcee8'
down_revision = 'df7e78400a3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('schedule', 'date',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedule', 'endtime',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('schedule', 'finished',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('schedule', 'frequency_association',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('schedule', 'release_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('schedule', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('schedule', 'starttime',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    op.alter_column('schedule', 'test_ids',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('schedule', 'timeofday',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('schedule', 'typeofactivity',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'confirmed_release_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'contamination_migrated_off_site',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('site_data', 'date_release_discovered',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'free_product_previously',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('site_data', 'free_product_recovered',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'free_product_recovered_since_last_report',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'groundwater_flow_direction',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'groundwater_remediated',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'groundwater_remediated_since_last_report',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'impacted_parties_notified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('site_data', 'maximum_mtbe_concentration',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('site_data', 'mera_site_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'michigan_rbca_site_classification',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site_data', 'mtbe_detected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('site_data', 'point_of_release_to_municipal_well',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'point_of_release_to_private_well',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'point_of_release_to_surface_water',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site_data', 'soil_remediated',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'soil_remediated_since_last_report',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'type_of_product_released',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_data', 'vapors_in_confined_space',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('substances_sites', 'substance_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('substances_sites', 'substance_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site_data', 'vapors_in_confined_space',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('site_data', 'type_of_product_released',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_data', 'soil_remediated_since_last_report',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_data', 'soil_remediated',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_data', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site_data', 'point_of_release_to_surface_water',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_data', 'point_of_release_to_private_well',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_data', 'point_of_release_to_municipal_well',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_data', 'mtbe_detected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('site_data', 'michigan_rbca_site_classification',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site_data', 'mera_site_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_data', 'maximum_mtbe_concentration',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('site_data', 'impacted_parties_notified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('site_data', 'groundwater_remediated_since_last_report',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_data', 'groundwater_remediated',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_data', 'groundwater_flow_direction',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_data', 'free_product_recovered_since_last_report',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_data', 'free_product_recovered',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_data', 'free_product_previously',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('site_data', 'date_release_discovered',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_data', 'contamination_migrated_off_site',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('site_data', 'confirmed_release_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('schedule', 'typeofactivity',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('schedule', 'timeofday',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('schedule', 'test_ids',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('schedule', 'starttime',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('schedule', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedule', 'release_number',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('schedule', 'frequency_association',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('schedule', 'finished',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('schedule', 'endtime',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('schedule', 'date',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedule', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
