"""added json fields to site

Revision ID: 93b5f572905d
Revises: b8f8d792bbeb
Create Date: 2017-05-06 00:27:35.917119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93b5f572905d'
down_revision = 'b8f8d792bbeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('test_ids', postgresql.JSON(), nullable=True))
    op.add_column('site', sa.Column('additional_consultant_ids', postgresql.JSON(), nullable=True))
    op.add_column('site', sa.Column('additional_owner_ids', postgresql.JSON(), nullable=True))
    op.add_column('site', sa.Column('qaqc_duplicates_test_ids', postgresql.JSON(), nullable=True))
    op.add_column('site', sa.Column('qaqc_duplicates_well_ids', postgresql.JSON(), nullable=True))
    op.add_column('site', sa.Column('qaqc_equipmentblanks_test_ids', postgresql.JSON(), nullable=True))
    op.add_column('site', sa.Column('qaqc_fieldblanks_test_ids', postgresql.JSON(), nullable=True))
    op.add_column('site', sa.Column('qaqc_msmsds_test_ids', postgresql.JSON(), nullable=True))
    op.add_column('site', sa.Column('qaqc_msmsds_well_ids', sa.String(length=255), nullable=True))
    op.add_column('site', sa.Column('qaqc_tripblanks_test_ids', postgresql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'qaqc_tripblanks_test_ids')
    op.drop_column('site', 'qaqc_msmsds_well_ids')
    op.drop_column('site', 'qaqc_msmsds_test_ids')
    op.drop_column('site', 'qaqc_fieldblanks_test_ids')
    op.drop_column('site', 'qaqc_equipmentblanks_test_ids')
    op.drop_column('site', 'qaqc_duplicates_well_ids')
    op.drop_column('site', 'qaqc_duplicates_test_ids')
    op.drop_column('site', 'additional_owner_ids')
    op.drop_column('site', 'additional_consultant_ids')
    op.drop_column('schedule', 'test_ids')
    # ### end Alembic commands ###
