"""add photo url

Revision ID: 96a6b0dbd5c3
Revises: 493fcfff5b0b
Create Date: 2017-03-10 16:35:23.097639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a6b0dbd5c3'
down_revision = '493fcfff5b0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab', sa.Column('photo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab', 'photo_url')
    # ### end Alembic commands ###
