"""switched sample models to dates from ints

Revision ID: 989a22a92ea0
Revises: ed5a1eafa7d4
Create Date: 2017-04-24 11:39:58.213276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989a22a92ea0'
down_revision = 'ed5a1eafa7d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('date_analyzed', sa.Date(), nullable=True))
    op.add_column('sample', sa.Column('date_collected', sa.Date(), nullable=True))
    op.add_column('sample', sa.Column('date_extracted', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'date_extracted')
    op.drop_column('sample', 'date_collected')
    op.drop_column('sample', 'date_analyzed')
    # ### end Alembic commands ###
