"""add test materials

Revision ID: 9e29256d1be0
Revises: b2c9c6a7e170
Create Date: 2017-02-10 00:31:33.900574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e29256d1be0'
down_revision = 'b2c9c6a7e170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_material',
    sa.Column('test_material_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('bottle', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('test_material_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_material')
    # ### end Alembic commands ###
