"""remove project manager from project

Revision ID: aa5469c7fd5a
Revises: ee2751348ba1
Create Date: 2017-03-28 17:27:11.562502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5469c7fd5a'
down_revision = 'ee2751348ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'project_project_manager_id_fkey', 'project', type_='foreignkey')
    op.drop_column('project', 'project_manager_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'project_project_manager_id_fkey', 'project', 'user', ['project_manager_id'], ['id'])
    # ### end Alembic commands ###
