"""added id to criteria_values

Revision ID: ab9ec5041688
Revises: ef256df5169c
Create Date: 2017-06-07 04:32:05.775519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9ec5041688'
down_revision = 'ef256df5169c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('criteria_values', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criteria_values', 'id')
    # ### end Alembic commands ###
