"""added url to sitemap model


Revision ID: b0351a9b353a
Revises: 0e37f0ff2675
Create Date: 2017-04-28 04:10:10.494618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0351a9b353a'
down_revision = '0e37f0ff2675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_map', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_map', 'url')
    # ### end Alembic commands ###
