"""added non_detect boolean to SampleValue model

Revision ID: b119ce789d28
Revises: 709d38298df2
Create Date: 2017-06-28 22:23:42.709694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b119ce789d28'
down_revision = '709d38298df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_value', sa.Column('non_detect', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_value', 'non_detect')
    # ### end Alembic commands ###
