"""added lab_upload bool to Upload to indicate if lab or use uploaded the file, fixes filtering issues on lab uploads view

Revision ID: b5bcde025b6e
Revises: 68c90ef0a089
Create Date: 2017-06-26 10:02:22.455724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bcde025b6e'
down_revision = '68c90ef0a089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('lab_upload', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'lab_upload')
    # ### end Alembic commands ###
