"""removed fields from site

Revision ID: b8f8d792bbeb
Revises: 0977b4626e1d
Create Date: 2017-05-06 00:26:54.036700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f8d792bbeb'
down_revision = '0977b4626e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'test_ids')
    op.drop_column('site', 'additional_consultant_ids')
    op.drop_column('site', 'qaqc_tripblanks_test_ids')
    op.drop_column('site', 'qaqc_duplicates_test_ids')
    op.drop_column('site', 'qaqc_fieldblanks_test_ids')
    op.drop_column('site', 'qaqc_duplicates_well_ids')
    op.drop_column('site', 'qaqc_msmsds_test_ids')
    op.drop_column('site', 'qaqc_msmsds_well_ids')
    op.drop_column('site', 'additional_owner_ids')
    op.drop_column('site', 'qaqc_equipmentblanks_test_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('qaqc_equipmentblanks_test_ids', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('additional_owner_ids', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_msmsds_well_ids', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_msmsds_test_ids', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_duplicates_well_ids', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_fieldblanks_test_ids', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_duplicates_test_ids', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('qaqc_tripblanks_test_ids', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('site', sa.Column('additional_consultant_ids', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('schedule', sa.Column('test_ids', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
