"""added uploads model and fixed foreignkey on site


Revision ID: ba8709fd7e32
Revises: 761e41a804fd
Create Date: 2017-03-21 17:12:38.349811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8709fd7e32'
down_revision = '761e41a804fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sample_date', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['lab_id'], ['lab.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'site_laboratory_id_fkey', 'site', type_='foreignkey')
    op.execute('ALTER TABLE public.site RENAME COLUMN laboratory_id TO lab_id')
    op.create_foreign_key(None, 'site', 'lab', ['lab_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload')
    op.drop_constraint(None, 'site', type_='foreignkey')
    op.execute('ALTER TABLE public.site RENAME COLUMN lab_id TO laboratory_id')
    op.create_foreign_key(u'site_laboratory_id_fkey', 'site', 'lab', ['laboratory_id'], ['id'])
    # ### end Alembic commands ###
