"""removed nullable false from all models


Revision ID: c883db906d19
Revises: 06e9881a7476
Create Date: 2017-04-24 11:28:30.326469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c883db906d19'
down_revision = '06e9881a7476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('company', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('consultant', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('consultant', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('consultant', 'cell',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('consultant', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('consultant', 'contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('consultant', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('consultant', 'fax',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('consultant', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('consultant', 'phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('consultant', 'qcid',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('consultant', 'state',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('consultant', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('consultant', 'zip',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('lab', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('lab', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('lab', 'cell',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('lab', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('lab', 'contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('lab', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('lab', 'fax',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('lab', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('lab', 'phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('lab', 'shipping_account',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('lab', 'shipping_company',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('lab', 'shipping_notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('lab', 'state',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('lab', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('lab', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('lab', 'zip',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('manager', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('manager', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('manager', 'cell',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('manager', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('manager', 'contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('manager', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('manager', 'fax',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('manager', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('manager', 'phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('manager', 'state',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('manager', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('manager', 'zip',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('office', 'address',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('office', 'city',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('office', 'lat',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('office', 'lng',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('office', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('office', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('office', 'zip',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('role_deprecated', 'access',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('role_deprecated', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('sample', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sample', 'date_analyzed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sample', 'date_collected',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sample', 'date_extracted',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sample', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sample_value', 'new',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sample_value', 'sample_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sample_value', 'substance_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sample_value', 'value',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('sample_value', 'well_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sampler', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sampler', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('sampler', 'cell',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('sampler', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('sampler', 'contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('sampler', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('sampler', 'fax',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('sampler', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('sampler', 'phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('sampler', 'state',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('sampler', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('sampler', 'zip',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('site_map', 'height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site_map', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site_map', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_map', 'width',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site_map_well', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site_map_well', 'site_map_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site_map_well', 'well_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site_map_well', 'xpos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site_map_well', 'xpos_fields',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site_map_well', 'ypos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('site_map_well', 'ypos_fields',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test', 'abbrev',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('test', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('test', 'field',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('test', 'filter',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('test', 'preservative',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('test', 'sort',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test', 'state_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test', 'substance_ids',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('test', 'test_material_ids',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('test', 'test_material_qty',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('test', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('test_material', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('test_material', 'bottle',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('test_material', 'sort',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_material', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tests_substances', 'substance_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tests_substances', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_deprecated', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('user_deprecated', 'failed_login_timestamp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_deprecated', 'hash_timestamp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_deprecated', 'login_failures',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_deprecated', 'login_timestamp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_deprecated', 'require_password_change',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_deprecated', 'suspended',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user_deprecated', 'user_role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_deprecated', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_deprecated', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('user_deprecated', 'user_role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_deprecated', 'suspended',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_deprecated', 'require_password_change',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user_deprecated', 'login_timestamp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_deprecated', 'login_failures',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_deprecated', 'hash_timestamp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_deprecated', 'failed_login_timestamp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_deprecated', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('tests_substances', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tests_substances', 'substance_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_material', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('test_material', 'sort',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_material', 'bottle',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('test_material', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('test', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('test', 'test_material_qty',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('test', 'test_material_ids',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('test', 'substance_ids',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('test', 'state_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test', 'sort',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test', 'preservative',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('test', 'filter',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('test', 'field',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('test', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('test', 'abbrev',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('site_map_well', 'ypos_fields',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site_map_well', 'ypos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site_map_well', 'xpos_fields',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site_map_well', 'xpos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site_map_well', 'well_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site_map_well', 'site_map_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site_map_well', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site_map', 'width',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site_map', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_map', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('site_map', 'height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sampler', 'zip',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('sampler', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sampler', 'state',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('sampler', 'phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('sampler', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('sampler', 'fax',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('sampler', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sampler', 'contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sampler', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('sampler', 'cell',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('sampler', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sampler', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sample_value', 'well_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sample_value', 'value',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('sample_value', 'substance_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sample_value', 'sample_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sample_value', 'new',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sample', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sample', 'date_extracted',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sample', 'date_collected',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sample', 'date_analyzed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sample', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('role_deprecated', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('role_deprecated', 'access',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('office', 'zip',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('office', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('office', 'state',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('office', 'lng',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('office', 'lat',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('office', 'city',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('office', 'address',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('manager', 'zip',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('manager', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('manager', 'state',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('manager', 'phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('manager', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('manager', 'fax',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('manager', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('manager', 'contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('manager', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('manager', 'cell',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('manager', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('manager', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('lab', 'zip',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('lab', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('lab', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('lab', 'state',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('lab', 'shipping_notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('lab', 'shipping_company',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('lab', 'shipping_account',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('lab', 'phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('lab', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('lab', 'fax',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('lab', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('lab', 'contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('lab', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('lab', 'cell',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('lab', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('lab', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('consultant', 'zip',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('consultant', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('consultant', 'state',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('consultant', 'qcid',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('consultant', 'phone',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('consultant', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('consultant', 'fax',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('consultant', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('consultant', 'contact',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('consultant', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('consultant', 'cell',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('consultant', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('consultant', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('company', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('company', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
