"""added abbreviation to Substance table

Revision ID: d2ea3620e79f
Revises: 25caf3f73fb8
Create Date: 2017-06-24 08:13:01.044313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ea3620e79f'
down_revision = '25caf3f73fb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('substance', sa.Column('abbreviation', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('substance', 'abbreviation')
    # ### end Alembic commands ###
