"""add tests

Revision ID: ddd5e9aeafa5
Revises: 9e29256d1be0
Create Date: 2017-02-10 14:24:11.881743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd5e9aeafa5'
down_revision = '9e29256d1be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('abbrev', sa.String(length=128), nullable=False),
    sa.Column('preservative', sa.String(length=255), nullable=False),
    sa.Column('filter', sa.String(length=255), nullable=False),
    sa.Column('field', sa.Boolean(), nullable=False),
    sa.Column('substance_ids', sa.Text(), nullable=False),
    sa.Column('test_material_ids', sa.Text(), nullable=False),
    sa.Column('test_material_qty', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['state.state_id'], ),
    sa.PrimaryKeyConstraint('test_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
