"""changed a bunch of well related tables to allow nullable values


Revision ID: df7e78400a3d
Revises: fb8439bf0caf
Create Date: 2017-04-06 00:58:12.825441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7e78400a3d'
down_revision = 'fb8439bf0caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frequency', 'default',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('frequency', 'peryear',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('frequency', 'sort',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('frequency', 'timediff',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('frequency', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('frequency', 'unit',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('well', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('well', 'depth_to_bottom',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('well', 'diameter',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('well', 'est_depth_to_water',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('well', 'frequency_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well', 'latitude',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('well', 'longitude',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('well', 'material',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('well', 'notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('well', 'purge_water_disposal',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('well', 'sampletechnique',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('well', 'screenlength',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('well', 'sort',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('well', 'top_of_casing',
               existing_type=sa.REAL(),
               nullable=True)
    op.alter_column('well', 'xpos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well', 'xpos_fields',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well', 'ypos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well', 'ypos_fields',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well_date', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('well_date', 'gaugeonly',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('well_date', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well_date', 'test_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('well_date', 'well_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well_date_set', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('well_date_set', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well_date_set', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well_image', 'height_md',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well_image', 'height_sm',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well_image', 'last_modified',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well_image', 'sort',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well_image', 'well_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well_image', 'width_md',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well_image', 'width_sm',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well_options', 'field',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('well_options', 'sort',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('well_options', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('well_options', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('well_options', 'sort',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well_options', 'field',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('well_image', 'width_sm',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well_image', 'width_md',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well_image', 'well_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well_image', 'sort',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well_image', 'last_modified',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well_image', 'height_sm',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well_image', 'height_md',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well_date_set', 'site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well_date_set', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well_date_set', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('well_date', 'well_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well_date', 'test_ids',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('well_date', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well_date', 'gaugeonly',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('well_date', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('well', 'ypos_fields',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well', 'ypos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well', 'xpos_fields',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well', 'xpos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well', 'top_of_casing',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('well', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('well', 'sort',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well', 'screenlength',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('well', 'sampletechnique',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('well', 'purge_water_disposal',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('well', 'notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('well', 'material',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('well', 'longitude',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('well', 'latitude',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('well', 'frequency_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('well', 'est_depth_to_water',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('well', 'diameter',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('well', 'depth_to_bottom',
               existing_type=sa.REAL(),
               nullable=False)
    op.alter_column('well', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('frequency', 'unit',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('frequency', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('frequency', 'timediff',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('frequency', 'sort',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('frequency', 'peryear',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('frequency', 'default',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
