"""deleting date fields from Sample

Revision ID: ed5a1eafa7d4
Revises: c883db906d19
Create Date: 2017-04-24 11:39:32.230526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed5a1eafa7d4'
down_revision = 'c883db906d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'date_collected')
    op.drop_column('sample', 'date_analyzed')
    op.drop_column('sample', 'date_extracted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('date_extracted', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sample', sa.Column('date_analyzed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sample', sa.Column('date_collected', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
