"""remove company relation from site

Revision ID: ee2751348ba1
Revises: 2d7b2ed17262
Create Date: 2017-03-27 05:12:53.085017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2751348ba1'
down_revision = '2d7b2ed17262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'site_company_id_fkey', 'site', type_='foreignkey')
    op.drop_column('site', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'site_company_id_fkey', 'site', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###
