"""added skipped_wells table

Revision ID: ef256df5169c
Revises: 5181de7d6275
Create Date: 2017-05-10 10:27:49.116133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef256df5169c'
down_revision = '5181de7d6275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skipped_wells',
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skipped_wells')
    # ### end Alembic commands ###
