"""add user roles and frequencies

Revision ID: f4bc69ce830e
Revises: c92efc26ffb5
Create Date: 2017-02-09 23:24:03.381802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4bc69ce830e'
down_revision = 'c92efc26ffb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequency',
    sa.Column('frequency_id', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('timediff', sa.String(length=64), nullable=False),
    sa.Column('peryear', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('frequency_id')
    )
    op.create_table('role',
    sa.Column('user_role_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('access', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_role_id')
    )
    op.create_foreign_key(None, 'user', 'role', ['user_role_id'], ['user_role_id'])
    op.drop_column(u'user', 'hash1')
    op.drop_column(u'user', 'hash')
    op.drop_column(u'user', 'hash3')
    op.drop_column(u'user', 'hash2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('hash2', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(u'user', sa.Column('hash3', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(u'user', sa.Column('hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(u'user', sa.Column('hash1', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_table('role')
    op.drop_table('frequency')
    # ### end Alembic commands ###
