"""added company_id fk to Site because each site belongs to a company

Revision ID: fb8439bf0caf
Revises: 34ccffafedd4
Create Date: 2017-04-04 09:41:14.850460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8439bf0caf'
down_revision = '34ccffafedd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'site', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site', type_='foreignkey')
    op.drop_column('site', 'company_id')
    # ### end Alembic commands ###
