
state = [
    (1, {'abbreviation': u'AL', 'id': 1, 'title': u'Alabama'}),
    (2, {'abbreviation': u'AK', 'id': 2, 'title': u'Alaska'}),
    (3, {'abbreviation': u'AZ', 'id': 3, 'title': u'Arizona'}),
    (4, {'abbreviation': u'AR', 'id': 4, 'title': u'Arkansas'}),
    (5, {'abbreviation': u'CA', 'id': 5, 'title': u'California'}),
    (6, {'abbreviation': u'CO', 'id': 6, 'title': u'Colorado'}),
    (7, {'abbreviation': u'CT', 'id': 7, 'title': u'Connecticut'}),
    (8, {'abbreviation': u'DE', 'id': 8, 'title': u'Delaware'}),
    (10, {'abbreviation': u'FL', 'id': 10, 'title': u'Florida'}),
    (11, {'abbreviation': u'GA', 'id': 11, 'title': u'Georgia'}),
    (12, {'abbreviation': u'HI', 'id': 12, 'title': u'Hawaii'}),
    (13, {'abbreviation': u'ID', 'id': 13, 'title': u'Idaho'}),
    (14, {'abbreviation': u'IL', 'id': 14, 'title': u'Illinois'}),
    (15, {'abbreviation': u'IN', 'id': 15, 'title': u'Indiana'}),
    (16, {'abbreviation': u'IA', 'id': 16, 'title': u'Iowa'}),
    (17, {'abbreviation': u'KS', 'id': 17, 'title': u'Kansas'}),
    (18, {'abbreviation': u'KY', 'id': 18, 'title': u'Kentucky'}),
    (19, {'abbreviation': u'LA', 'id': 19, 'title': u'Louisiana'}),
    (20, {'abbreviation': u'ME', 'id': 20, 'title': u'Maine'}),
    (21, {'abbreviation': u'MT', 'id': 21, 'title': u'Montana'}),
    (22, {'abbreviation': u'NE', 'id': 22, 'title': u'Nebraska'}),
    (23, {'abbreviation': u'NV', 'id': 23, 'title': u'Nevada'}),
    (24, {'abbreviation': u'NH', 'id': 24, 'title': u'New Hampshire'}),
    (25, {'abbreviation': u'NJ', 'id': 25, 'title': u'New Jersey'}),
    (26, {'abbreviation': u'NM', 'id': 26, 'title': u'New Mexico'}),
    (27, {'abbreviation': u'NY', 'id': 27, 'title': u'New York'}),
    (28, {'abbreviation': u'NC', 'id': 28, 'title': u'North Carolina'}),
    (29, {'abbreviation': u'ND', 'id': 29, 'title': u'North Dakota'}),
    (30, {'abbreviation': u'OH', 'id': 30, 'title': u'Ohio'}),
    (31, {'abbreviation': u'OK', 'id': 31, 'title': u'Oklahoma'}),
    (32, {'abbreviation': u'OR', 'id': 32, 'title': u'Oregon'}),
    (33, {'abbreviation': u'MD', 'id': 33, 'title': u'Maryland'}),
    (34, {'abbreviation': u'MA', 'id': 34, 'title': u'Massachusetts'}),
    (35, {'abbreviation': u'MI', 'id': 35, 'title': u'Michigan'}),
    (36, {'abbreviation': u'MN', 'id': 36, 'title': u'Minnesota'}),
    (37, {'abbreviation': u'MS', 'id': 37, 'title': u'Mississippi'}),
    (38, {'abbreviation': u'MO', 'id': 38, 'title': u'Missouri'}),
    (39, {'abbreviation': u'PA', 'id': 39, 'title': u'Pennsylvania'}),
    (40, {'abbreviation': u'RI', 'id': 40, 'title': u'Rhode Island'}),
    (41, {'abbreviation': u'SC', 'id': 41, 'title': u'South Carolina'}),
    (42, {'abbreviation': u'SD', 'id': 42, 'title': u'South Dakota'}),
    (43, {'abbreviation': u'TN', 'id': 43, 'title': u'Tennessee'}),
    (44, {'abbreviation': u'TX', 'id': 44, 'title': u'Texas'}),
    (45, {'abbreviation': u'UT', 'id': 45, 'title': u'Utah'}),
    (46, {'abbreviation': u'VT', 'id': 46, 'title': u'Vermont'}),
    (47, {'abbreviation': u'VA', 'id': 47, 'title': u'Virginia'}),
    (48, {'abbreviation': u'WA', 'id': 48, 'title': u'Washington'}),
    (49, {'abbreviation': u'WV', 'id': 49, 'title': u'West Virginia'}),
    (50, {'abbreviation': u'WI', 'id': 50, 'title': u'Wisconsin'}),
    (51, {'abbreviation': u'WY', 'id': 51, 'title': u'Wyoming'}),
]
