
substance_group = [
    (1, {'active': True, 'sort': 12, 'title': u'Gasoline Constituents', 'id': 1, 'hard_ref': 1}),
    (2, {'active': True, 'sort': 16, 'title': u'PNAs / PAHs', 'id': 2, 'hard_ref': 0}),
    (3, {'active': False, 'sort': 9, 'title': u'MTBE', 'id': 3, 'hard_ref': 0}),
    (10, {'active': True, 'sort': 3, 'title': u'Standard Field Tests', 'id': 10, 'hard_ref': 1}),
    (11, {'active': False, 'sort': 10, 'title': u'1, 2-Dibromoethane (ethylene dibromide EDB)', 'id': 11, 'hard_ref': 0}),
    (12, {'active': False, 'sort': 11, 'title': u' 1, 2-Dichloroethane', 'id': 12, 'hard_ref': 0}),
    (13, {'active': False, 'sort': 13, 'title': u'Dissolved Lead', 'id': 13, 'hard_ref': 0}),
    (14, {'active': False, 'sort': 1, 'title': u'BTEX Plus 7', 'id': 14, 'hard_ref': 0}),
    (15, {'active': True, 'sort': 20, 'title': u'Heavy Metals', 'id': 15, 'hard_ref': 0}),
    (16, {'active': True, 'sort': 15, 'title': u'VOCs', 'id': 16, 'hard_ref': 0}),
    (17, {'active': True, 'sort': 22, 'title': u'Nutrients', 'id': 17, 'hard_ref': 0}),
    (18, {'active': False, 'sort': 18, 'title': u'Unleaded Gasoline Michgan', 'id': 18, 'hard_ref': 0}),
    (19, {'active': False, 'sort': 19, 'title': u'NC-Unleaded gas', 'id': 19, 'hard_ref': 0}),
    (20, {'active': True, 'sort': 23, 'title': u'Mercury', 'id': 20, 'hard_ref': 0}),
    (21, {'active': False, 'sort': 21, 'title': u'New Substance Group', 'id': 21, 'hard_ref': 0}),
    (22, {'active': True, 'sort': 24, 'title': u'Chloride', 'id': 22, 'hard_ref': 0}),
    (23, {'active': True, 'sort': 25, 'title': u'Sulfate', 'id': 23, 'hard_ref': 0}),
    (24, {'active': True, 'sort': 26, 'title': u'Nitrate', 'id': 24, 'hard_ref': 0}),
    (25, {'active': True, 'sort': 27, 'title': u'Nitrite', 'id': 25, 'hard_ref': 0}),
    (26, {'active': True, 'sort': 28, 'title': u'Nitrate + Nitrite', 'id': 26, 'hard_ref': 0}),
    (27, {'active': False, 'sort': 29, 'title': u'Dissolved Lead, EPA 200.8', 'id': 27, 'hard_ref': 0}),
    (28, {'active': True, 'sort': 30, 'title': u'Oil & Grease', 'id': 28, 'hard_ref': 0}),
    (29, {'active': True, 'sort': 31, 'title': u'Chemical Oxygen Demand', 'id': 29, 'hard_ref': 0}),
    (30, {'active': True, 'sort': 32, 'title': u'Total Suspended Solids', 'id': 30, 'hard_ref': 0}),
    (31, {'active': True, 'sort': 33, 'title': u'Bromine', 'id': 31, 'hard_ref': 0}),
    (32, {'active': True, 'sort': 34, 'title': u'Total Dissolved Solids', 'id': 32, 'hard_ref': 0}),
    (33, {'active': True, 'sort': 35, 'title': u'Color', 'id': 33, 'hard_ref': 0}),
    (34, {'active': True, 'sort': 36, 'title': u'Total Recoverable Petroleum Hydrocarbons', 'id': 34, 'hard_ref': 0}),
    (35, {'active': True, 'sort': 38, 'title': u'CTAS', 'id': 35, 'hard_ref': 0}),
    (36, {'active': True, 'sort': 37, 'title': u'Sulfide', 'id': 36, 'hard_ref': 0}),
    (37, {'active': True, 'sort': 39, 'title': u'OC Pesticides', 'id': 37, 'hard_ref': 0}),
    (38, {'active': True, 'sort': 14, 'title': u'MTBE', 'id': 38, 'hard_ref': 0}),
    (39, {'active': True, 'sort': 40, 'title': u'Formaldehyde Method 8315A', 'id': 39, 'hard_ref': 0}),
    (40, {'active': True, 'sort': 41, 'title': u'PLFA', 'id': 40, 'hard_ref': 0}),
    (41, {'active': True, 'sort': 42, 'title': u'Gases', 'id': 41, 'hard_ref': 0}),
    (42, {'active': True, 'sort': 43, 'title': u'Total Organic Carbon (TOC)', 'id': 42, 'hard_ref': 0}),
    (43, {'active': True, 'sort': 17, 'title': u'SVOCs', 'id': 43, 'hard_ref': 0}),
    (44, {'active': True, 'sort': 44, 'title': u'Ethanol', 'id': 44, 'hard_ref': 0}),
    (45, {'active': True, 'sort': 45, 'title': u'Alkalinity', 'id': 45, 'hard_ref': 0}),
    (46, {'active': True, 'sort': 46, 'title': u'PCBs', 'id': 46, 'hard_ref': 0}),
    (47, {'active': True, 'sort': 47, 'title': u'Other', 'id': 47, 'hard_ref': 0}),
]
